using Google.Cloud.Firestore;
using Umbrella.Infrastructure.Firestore.Abstractions;
using Umbrella.Infrastructure.Firestore.Extensions;

namespace Umbrella.Infrastructure.Firestore.Tests
{
    [FirestoreData]
    public class TestEntityDocument : IBaseFirestoreData
    {
        [FirestoreDocumentId]
        public string Id { get; private set; }

        [FirestoreProperty]
        public string Name { get; set; }

        [FirestoreProperty]
        public DateTime CreatedOn { get; set; }

        [FirestoreProperty]
        public DateTime? LastUpdatedOn { get; set;}

        [FirestoreProperty]
        public int Counter {get; set;}

        public TestEntityDocument()
        {
            this.Id = "";
            this.Name = "";
            this.CreatedOn = DateTime.Now.ToFirestoreTimeStamp();
            this.LastUpdatedOn = null;
        }
        public void SetDocumentId(string id)
        {
            this.Id = id;
        }
    }

    public class BaseRepositoryTests
    {
        string _ProjectId;
        string _CredentialFilePath;

        [SetUp]
        public void Setup()
        {
            this._ProjectId = "umbrella-dev-369813";
            this._CredentialFilePath = @"C:\Users\francesco\OneDrive\Coding\umbrella-dev-azuredevops.json";
        }

        #region Private Methods
        BaseRepository<TestEntityDocument> InstanceRepostiory(string collectionName = "TestEntity", bool autogenerateId = false)
        {
            var variableValue = Environment.GetEnvironmentVariable("GOOGLE_APPLICATION_CREDENTIALS");
            if (String.IsNullOrEmpty(variableValue))
                Environment.SetEnvironmentVariable("GOOGLE_APPLICATION_CREDENTIALS", Path.GetFullPath(this._CredentialFilePath));
            return new BaseRepository<TestEntityDocument>(this._ProjectId, collectionName, autogenerateId);
        }
        #endregion

        [Test]
        public void Constructor_ThrowEx_IfProjectIdIsNull()
        {
            //******* GIVEN
            string projectId = "";
            string collectionName = "TestEntity";

            //******* WHEN
            ArgumentNullException ex = Assert.Throws<ArgumentNullException>(() => new BaseRepository<TestEntityDocument>(projectId, collectionName, true));
            Assert.That(ex.ParamName, Is.EqualTo("projectId"));
            Assert.Pass();
        }

        [Test]
        public void Constructor_ThrowEx_IfCollectionNameIsNull()
        {
            //******* GIVEN
            string projectId = "test";
            string collectionName = "";

            //******* WHEN
            ArgumentNullException ex = Assert.Throws<ArgumentNullException>(() => new BaseRepository<TestEntityDocument>(projectId, collectionName, true));
            Assert.That(ex.ParamName, Is.EqualTo("collectionName"));
            Assert.Pass();
        }

        [Test]
        public void Constructor_ThrowEx_IfAspNetVariableForCredentialIsNull()
        {
            //******* GIVEN
            string projectId = "test";
            string collectionName = "TestEntity";

            //******* WHEN
            InvalidOperationException ex = Assert.Throws<InvalidOperationException>(() => new BaseRepository<TestEntityDocument>(projectId, collectionName, true));
            Assert.That(ex.Message.StartsWith("The Application Default Credentials are not available.", true, System.Globalization.CultureInfo.InvariantCulture), 
                        Is.EqualTo(true));
            Assert.Pass();
        }

        [Test]
        public void AddAsync_CreatesNewDocument()
        {
            //******* GIVEN
            var id = Guid.NewGuid().ToString();
            var testEntity = new TestEntityDocument()
            {
                Counter = 22
            };
            testEntity.SetDocumentId(id);
            var repo = InstanceRepostiory();

            //******* WHEN
            var existingEntity =  repo.AddAsync(testEntity).Result as TestEntityDocument;

            //******* ASSERT
            Assert.False(existingEntity == null);
            Assert.That(existingEntity.Id, Is.EqualTo(id));
            Assert.Pass();
        }

        [Test]
        public void AddAsync_WIthAutoGeneratedId_CreatesNewDocumentWithDIfferentIdEvent_ItIsSet()
        {
            //******* GIVEN
            var id = Guid.NewGuid().ToString();
            var testEntity = new TestEntityDocument()
            {
                Counter = 22
            };
            testEntity.SetDocumentId(id);
            var repo = InstanceRepostiory(autogenerateId: true);

            //******* WHEN
            var existingEntity = repo.AddAsync(testEntity).Result as TestEntityDocument;

            //******* ASSE
            Assert.False(existingEntity == null);
            Assert.That(existingEntity.Id, Is.Not.EqualTo(id));
            Assert.Pass();
        }

        [Test]
        public void AddAsync_WithAutoGeneratedId_CreatesNewDocumentWithIdIfNotSet()
        {
            //******* GIVEN
            var testEntity = new TestEntityDocument()
            {
                Counter = 22
            };
            var repo = InstanceRepostiory(autogenerateId: true);

            //******* WHEN
            var existingEntity = repo.AddAsync(testEntity).Result as TestEntityDocument;

            //******* ASSE
            Assert.False(existingEntity == null);
            Assert.That(existingEntity.Id, Is.Not.EqualTo(""));
            Assert.Pass();
        }

        [Test]
        public void AddAsync_PersistsDocument_WithExpecetdValues()
        {
            //******* GIVEN
            var id = Guid.NewGuid().ToString();
            var creationDate = DateTime.Now.ToFirestoreTimeStamp();
            var testEntity = new TestEntityDocument()
            {
                Counter = 22,
                Name = "XXX",
                CreatedOn = creationDate
            };
            testEntity.SetDocumentId(id);
            var repo = InstanceRepostiory();

            //******* WHEN
            var existingEntity = repo.AddAsync(testEntity).Result as TestEntityDocument;

            //******* ASSE
            Assert.False(existingEntity == null);
            Assert.That(existingEntity.Id, Is.EqualTo(id));
            Assert.That(existingEntity.Name, Is.EqualTo("XXX"));
            Assert.That(existingEntity.Counter, Is.EqualTo(22));
            Assert.That(existingEntity.CreatedOn, Is.EqualTo(creationDate));

            var readEntity = repo.GetAsync(testEntity).Result as TestEntityDocument;
            Assert.False(readEntity == null);
            Assert.That(readEntity.Id, Is.EqualTo(id));
            Assert.That(readEntity.Name, Is.EqualTo("XXX"));
            Assert.That(readEntity.Counter, Is.EqualTo(22));
            Assert.That(readEntity.CreatedOn, Is.EqualTo(creationDate));
            Assert.Pass();
        }
    }
}